engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
checks:
  method-lines:
    config:
      threshold: 50
  similar-code:
    enabled: false

ratings:
  paths:
  - src

exclude_paths: 
  - android
  - ios
  - __tests_